version: '3.8'

services:
  backend:
    image: licitia-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  licitia_v29_debug:
    image: licitia-v29-debug:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - NEXT_PUBLIC_API_URL=https://licitia.allanturing.com/api
      - HOSTNAME=0.0.0.0
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: overlay